### ISSUE TITLE
Error scanning entry from jar, caused by ASM7 requirement

### ISSUE THREAD

**Issue by AHijner** [pepstock-org/Charba#91]
Hi

We're currently running Charba 6.0 after updating some weeks ago. Everything seems to be working alright, except for alot of suppressed errors/warnings we get at startup:

```
wt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/treemap/TreeMapElement.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/treemap/TreeMapElementOptions$Property.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/treemap/TreeMapElementOptions$TreeMapElementOptionsFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/treemap/TreeMapElementOptions.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/CScheduler$RunnableWrapper$Status.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/CScheduler$RunnableWrapper.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/CScheduler.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/CTimer$Status.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/CTimer.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/JSON$Replacer.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/JSON.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/Window$AsyncCallback.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/utils/Window.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, ... java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/zoom/ZoomOptionsFactory$ZoomDefaultsOptionsFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/zoom/ZoomOptionsFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar]
	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:536)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:447)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:479)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1337)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:550)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:760)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:636)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:898)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:705)
	at com.google.gwt.dev.DevMode.main(DevMode.java:432)
	Suppressed: MultiException[java.lang.RuntimeException: Error scanning file ZermeloRestTemplate$1$1.class, java.lang.RuntimeException: Error scanning file ZermeloRestTemplate$1.class, java.lang.RuntimeException: Error scanning file ZermeloRestTemplate.class]
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:681)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:688)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:688)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:688)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:688)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:688)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:688)
		at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:824)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
		at java.base/java.lang.Thread.run(Thread.java:829)
		Suppressed: java.lang.RuntimeException: Error scanning file ZermeloRestTemplate$1.class
			at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:708)
			... 12 more
		Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:702)
			... 12 more
		Suppressed: java.lang.RuntimeException: Error scanning file ZermeloRestTemplate.class
			at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:708)
			... 12 more
		Caused by: java.lang.UnsupportedOperationException: NestMember requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:251)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:696)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:702)
			... 12 more
	Caused by: java.lang.RuntimeException: Error scanning file ZermeloRestTemplate$1$1.class
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:708)
		... 12 more
	Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
		at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
		at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:702)
		... 12 more
	Suppressed: MultiException[java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$ActiveElementsPoint.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$ChartRunnableWrapper.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$DatasetItemFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$DatasetReferenceFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/Configuration$Property.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/Configuration.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/Defaults$InternalDefaultScale.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/Defaults$InternalDefaultScales.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/Defaults$NativeChartHandler.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar,

...

 java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/zoom/ZoomOptions.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/zoom/ZoomOptionsFactory$ZoomDefaultsOptionsFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar, java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/zoom/ZoomOptionsFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar]
		at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:899)
		at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
		at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
		at java.base/java.lang.Thread.run(Thread.java:829)
		Suppressed: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$ChartRunnableWrapper.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
			... 6 more
		Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
			... 6 more
		Suppressed: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$DatasetItemFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
			... 6 more
		Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
			... 6 more
		Suppressed: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$DatasetReferenceFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
			... 6 more
		Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
			... 6 more
		Suppressed: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
			... 6 more
		Caused by: java.lang.UnsupportedOperationException: NestMember requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:251)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:696)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
			... 6 more
		Suppressed: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/Configuration$Property.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
			... 6 more
		Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
			... 6 more

...


		Suppressed: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/zoom/ZoomOptionsFactory$ZoomDefaultsOptionsFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
			... 6 more
		Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
			... 6 more
		Suppressed: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/zoom/ZoomOptionsFactory.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
			... 6 more
		Caused by: java.lang.UnsupportedOperationException: NestMember requires ASM7
			at org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:251)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:696)
			at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
			at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
			at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
			... 6 more
	Caused by: java.lang.RuntimeException: Error scanning entry org/pepstock/charba/client/AbstractChart$ActiveElementsPoint.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/charba-6.2-gwt.jar
		at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
		... 6 more
	Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
		at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
		at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
		at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
		at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
		... 6 more
Caused by: java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/C:/Users/ahijner/AppData/Local/JetBrains/IntelliJIdea2021.2/gwt/portal.e2dfe245/main.d053ffde/run/www/WEB-INF/lib/asm-9.2.jar
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedOperationException: Module requires ASM6
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:145)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:781)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:580)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909)
	... 6 more
2023-03-16 14:49:28.849:INFO:oejs.ServerConnector:main: Started ServerConnector@52dec2e6{HTTP/1.1}{127.0.0.1:8888}
2023-03-16 14:49:28.850:INFO:oejs.Server:main: Started @56176ms
Dev Mode initialized. Startup URL:
http://localhost:8443/
```

We are using ASM 9.2, changing it to any version of 7.x does not influence these errors, nor does updating Charba to version 6.1 or 6.2. We are wondering if Charba or Chart.js somehow specify which version of ASM to use?

Since our application is running fine otherwise, it's not a huge issue, but it might hide any other future errors from us, so we would like to solve it if at all possible.

Additional info: we are running Java 11 and GWT 2.9.0

**Comment by stockiNail** [comment]
@AHijner It's weird... 

> We are wondering if Charba or Chart.js somehow specify which version of ASM to use?

No, Charba is not using ASM. We don't have any runtime dependencies, because we assume that Charba is leveraging on GWT and its JSInterop annotation implementation. No other dependencies.

Currently I'm using OpenJDK 11 and GWT 2.9 without any issue.
It seems you are using IntellJ that I'm not using but I don't think it could be related. Let me do some investigation to understand what could be.

**Comment by stockiNail** [comment]
@AHijner I had a look to GWT 2.9.0 dependencies and it has the dependency with ASM 7.1 (https://mvnrepository.com/artifact/com.google.gwt/gwt-dev/2.9.0).

Are you using maven to get the GWT dependencies or the GWT SDK (where ASM is embedded)?

**Comment by AHijner** [comment]
From what I understand, the warnings/errors occur when using the JetBrains GWT plugin in IntelliJ, which indeed seems to have ASM embedded. Most of my team use this method. However, when using maven instead, I indeed don't see the same errors. 
As the GWT plugin does seem to have ASM 7.x, the error that ASM7 is required still confuses me. Perhaps the exact versions don't match or something.
I'll discuss with my team if instead we can all use maven to get the GWT dependencies, or if we would really like to keep using the GWT plugin.

**Comment by stockiNail** [comment]
@AHijner thank you very much for feedback! Maybe this link in Google groups could help: https://groups.google.com/g/google-web-toolkit/c/l_E1Y8XKg7k/m/wap_721jBwAJ

**Comment by stockiNail** [comment]
@AHijner I think we can close this issue because not strictly related to Charba. Feel free to reopen if needed.
